#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <stdio.h>
#include "mmm.h"

/**
 * Allocate and initialize the matrices on the heap. Populate
 * the input matrices with random integers from 0 to 99
 */
void mmm_init() {
	inputA = (int**) malloc(sizeof(int*) * matSize);
	inputB = (int**) malloc(sizeof(int*) * matSize);
	output = (int**) malloc(sizeof(int*) * matSize);
	for (int i = 0; i < matSize; i++){
		inputA[i] = (int*) malloc(sizeof(int) * matSize);
		inputB[i] = (int*) malloc(sizeof(int) * matSize);
		output[i] = (int*) malloc(sizeof(int) * matSize);
	}
	for (int i = 0; i < matSize; i++){
		for (int j = 0; j < matSize; j++){
			inputA[i][j] = rand() % 100;
			inputB[i][j] = rand() % 100;
		}
	}
	printf("Resultant matrix A:\n");
    for (int i = 0; i < matSize; i++) {
        for (int j = 0; j < matSize; j++) {
            printf("%d ", inputA[i][j]);
        }
        printf("\n");
    }
}

/**
 * Reset a given matrix to zeroes
 * @param matrix pointer to a 2D array
 */
void mmm_reset(double **matrix) {
	// TODO
}

/**
 * Free up memory allocated to all matrices
 */
void mmm_freeup() {
	for (int i = 0; i < matSize; i++) {
    	free(inputA[i]);
		free(inputB[i]);
		free(output[i]);
    	inputA[i] = NULL;  // remove dangling pointer
    	inputB[i] = NULL;
    	output[i] = NULL;
 	}
	free(inputA);
	free(inputB);
	free(output);
}

/**
 * Sequential MMM
 */
void mmm_seq() {
	// TODO - code to perform sequential MMM
}

/**
 * Parallel MMM
 */
void *mmm_par(void *args) {
	// TODO - code to perform parallel MMM
	return NULL;
}

/**
 * Verifies the correctness between the matrices generated by
 * the sequential run and the parallel run.
 *
 * @return the largest error between two corresponding elements
 * in the result matrices
 */
double mmm_verify() {
	// TODO
	return -1;
}
